# Generated by Django 4.2.2 on 2023-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apikey',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
