# Generated by Django 4.2.2 on 2023-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apikey',
            field=models.TextField(),
        ),
    ]
